#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

rm -rf $OPENSHIFT_REPO_DIR/upload
echo "...............pre_build............creating symlinks................."
if [ ! -d "$OPENSHIFT_DATA_DIR/upload" ]; then
    mkdir $OPENSHIFT_DATA_DIR/upload
    echo directory made.
fi
ln -sf $OPENSHIFT_DATA_DIR/upload $OPENSHIFT_REPO_DIR/upload
echo ".............creating symlinks completed........................"